version: "3.1"
services: 
  mysql:
    container_name: rc_mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=${RC_DB_DEV_DB_NAME}
      - MYSQL_USER=${RC_DB_USER}
      - MYSQL_PASSWORD=${RC_DB_PASS}
  adminer:
    image: adminer
    depends_on: 
      - mysql
    ports: 
      - 8080:8080
